# Generated by Django 5.0.3 on 2024-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='filiere',
            field=models.CharField(choices=[('INFO', 'Informatique Fondemmentale'), ('PHYS', 'Physique'), ('CHIM', 'Chimie'), ('MATH', 'Mathématiques'), ('BIO', 'Science Biologie'), ('SCIE', 'Science Environnementale')], max_length=4),
        ),
    ]
